# Introduction

Every automation team today faces a split personality. On one side live deterministic systems—API calls, database updates, human approvals—that demand precise orchestration and audit-ready histories. On the other side sit increasingly capable AI agents that can summarize, synthesize, and decide with breathtaking flexibility but stubborn nondeterminism. The open specification you are about to read exists to reconcile those worlds. It gives platforms, builders, and reviewers a common language for weaving together modular programmatic steps with agentic intelligence without turning every implementation into bespoke glue code.

This document is intentionally narrative-first. It starts by explaining why interoperability matters when the underlying engines, models, and connectors change weekly. It then walks through the architectural building blocks—workflow envelopes, step catalogs, data contracts, guardrails—that make automation predictable, even when powered by probabilistic models. Along the way, you will see how human-in-the-loop checkpoints, observability, and governance protocols are treated as first-class citizens, not afterthoughts bolted on at deployment time.

While the clauses that follow use normative language to stay unambiguous, the goal is inclusivity. Architects should be able to map the requirements onto their execution engines; designers should recognize how intent is preserved from whiteboard to runtime; auditors should find the controls they need to trust AI-assisted operations. The annexes round out the story with worked examples, schema fragments, and glossaries so that adopting the spec does not require deciphering undocumented assumptions.

If you are building or reviewing AI-driven workflows, treat this introduction as an invitation: a roadmap for how the specification brings deterministic confidence and creative intelligence under the same roof. The pages that follow turn that promise into actionable detail.
